spring:
  application:
    name: find-you
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
      type:
        descriptor:
          sql:
            BasicBinder: TRACE