version: '3.8'

services:
  db:
    image: mysql:8.0.3
    container_name: find-you
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: findyou