version: '3.8'

services:
  mysql:
    image: mysql:9.3.0-1.el9
    container_name: find-you
    environment:
      MYSQL_ROOT_PASSWORD: 920214
      MYSQL_DATABASE: findyou
      MYSQL_USER: aksrua
      MYSQL_PASSWORD: 920214
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - find-you

networks:
  spring-mysql-network:
    driver: find-you

volumes:
  mysql-data: